### ISSUE TITLE
complie errors, errors by winniethepoorbear not fixed...

### ISSUE THREAD

**Issue by AntonBoot** [exskye/sourcemod#16]
hope project not dead yet.  working over code find same errors posted by winniepoobear.  change my version but compile errors.  update l4d2d_internals.inc from author github and compile no error.  rum_dynamicslots.sp  not compile, error.   you need fix this I cant.

**Comment by psycki** [comment]
use the version of the original repository, to compile those who gave errors when compiling.
this link https://github.com/ConfoglTeam/l4d2_direct

**Comment by exskye** [comment]
psycki, does that version work? I have been including the version of l4d2_direct that I use, since some users reported problems with the new version not working properly. But if it works, I'll remove l4d2_direct files from this repository.

**Comment by psycki** [comment]
hello
I do not know what the difference of your l4d2_direct to the original, but when compiling with your version, it features the following errors,

//// rum_norush.sp
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(264) : error 021: symbol already defined: "GetEntityAddress"
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(266) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(268) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(271) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(274) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(276) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(281) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(283) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(286) : error 010: invalid function or declaration
// rum_norush.sp(270) : warning 203: symbol is never used: "GetBaseEntitySDKCall
"
//
// 9 Errors.
//
// Compilation Time: 0,3 sec
// ----------------------------------------

//// rum_rpg.sp
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(264) : error 021: symbol already defined: "GetEntityAddress"
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(266) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(268) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(271) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(274) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(276) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(281) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(283) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(286) : error 010: invalid function or declaration
// rum_rpg.sp(270) : warning 203: symbol is never used: "GetBaseEntitySDKCall"
//
// 9 Errors.
//
// Compilation Time: 1,86 sec
// ----------------------------------------

//// rum_teammanager.sp
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(264) : error 021: symbol already defined: "GetEntityAddress"
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(266) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(268) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(271) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(274) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(276) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(281) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(283) : error 010: invalid function or declaration
// C:\Users\psycki\Desktop\L4d1\addons\sourcemod\Nova pasta\scripting\include\l4
d2d_internals.inc(286) : error 010: invalid function or declaration
// rum_teammanager.sp(270) : warning 203: symbol is never used: "GetBaseEntitySD
KCall"
//
// 9 Errors.
//
// Compilation Time: 0,47 sec
// ----------------------------------------

and if I compile with the original it does not show any error.
I also had problems to compile other plugins with your version,
the detail is that I'm using windows 7 64 with sm1.6.3. I leave this report for you based on windows, because I have not installed linux to know if the same occurs.


Happy new year with a little backwardness ^^

note: Congratulations for your great job and commitment to this plugin. is one of the best plugins.

**Comment by exskye** [comment]
Hm, this is really strange... When I compiled SkyRPG v3.0.1 yesterday, I used the same version as I've uploaded here, with no error. But, if a different version works for you, that's great. I guess someone would need to get hold of prodigysim to get him to comment on this, to really know for sure.

Thanks psycki. I'm doing my best to continually update it. I receive emails from people with feature requests, comments, and other things, and am trying to implement them. I'm incredibly busy, and don't actually have access to a server to test the updates on, but I have some faith that they should still function properly.

I'll begin working on the next large update sometime this week, hopefully. It would be great to have contributors helping to develop, and potentially attract interest from more server communities interested in a plugin like this.
